// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCTI0kpbZ7rGdYmM8Vj9VRvjf-HUbCyXE',
    appId: '1:535138985357:web:dfb2dbce418d3fce5289c4',
    messagingSenderId: '535138985357',
    projectId: 'vaganzamovie',
    authDomain: 'vaganzamovie.firebaseapp.com',
    storageBucket: 'vaganzamovie.appspot.com',
    measurementId: 'G-MWMGDN932L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYE7Gd29Ctune7kcA0PZjnVQ_rpjgmsDU',
    appId: '1:535138985357:android:aa0161318a77a1745289c4',
    messagingSenderId: '535138985357',
    projectId: 'vaganzamovie',
    storageBucket: 'vaganzamovie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx2gysQHmzUZ7tismqpP8AHlwy-1lhaqg',
    appId: '1:535138985357:ios:8447287bfdab3f1e5289c4',
    messagingSenderId: '535138985357',
    projectId: 'vaganzamovie',
    storageBucket: 'vaganzamovie.appspot.com',
    iosBundleId: 'com.example.vaganzaMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx2gysQHmzUZ7tismqpP8AHlwy-1lhaqg',
    appId: '1:535138985357:ios:db14a9ed907409db5289c4',
    messagingSenderId: '535138985357',
    projectId: 'vaganzamovie',
    storageBucket: 'vaganzamovie.appspot.com',
    iosBundleId: 'com.example.vaganzaMovie.RunnerTests',
  );
}
